version: "3.9"

services:

  api:
    build:
      context: .
      args:
        BUILD_ENV: local
    container_name: celery_service
    command: [ uvicorn, --host=0.0.0.0, --port=7000,
               --log-config=uvicorn.json, src.main:app,
               --ssl-certfile=certs/public-cert.pem, --ssl-keyfile=certs/private-key.pem ]
    ports:
      - "8200:7000"
    secrets:
      - service_api_key
      - mongo_url_local
      - rabbit_url_root_local
    depends_on:
      - dashboard
      - worker
    environment:
      - ENVIRONMENT=local
    networks:
      - service_net

  worker:
    build:
      context: .
      args:
        BUILD_ENV: local
    container_name: celery_worker
    command: [ celery, --app=src.tasks, worker, --loglevel=info, --task-events ]
    secrets:
      - service_api_key
      - mongo_url_local
      - rabbit_url_root_local
    environment:
      - ENVIRONMENT=local
    networks:
      - service_net

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.flower
    container_name: celery_dashboard
    command: [ celery, --broker=amqp://guest:guest@rabbitmq/%2F,
               flower, --broker-api=http://guest:guest@rabbitmq:15672/api/ ]
    ports:
      - "5555:5555"
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
    networks:
      - service_net

secrets:
  service_api_key:
    file: C:/Users/ander/AppData/Roaming/Python/secrets/service_api_key
  mongo_url_local:
    file: C:/Users/ander/AppData/Roaming/Python/secrets/mongo_url_local
  rabbit_url_root_local:
    file: C:/Users/ander/AppData/Roaming/Python/secrets/rabbit_url_root_local

networks:
  service_net:
    external: true
    name: custom_network
